config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  resources :reviews, only: [:index, :new, :create]
end

app/models/review.rb
class Review < ActiveRecord::Base
  default_scope -> { order(created_at: :desc) }

  validates :name, presence: true
  validates :body, presence: true
  validates :relationship, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:show, :edit, :update, :destroy]

  # GET /reviews
  def index
    @reviews = Review.all
  end

  # GET /reviews/new
  def new
    @review = Review.new
  end

  # POST /reviews
  def create
    @review = Review.new(review_params)

    if @review.save
      redirect_to reviews_path, notice: "Thank you for your review!"
    else
      render :new
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_review
    @review = Review.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def review_params
    params.require(:review).permit(:body, :name, :relationship)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flashes_helper.rb
module FlashesHelper
  def user_facing_flashes
    flash.to_hash.slice("alert", "error", "notice", "success")
  end
end

app/views/application/_analytics.html.erb
<% if ENV["SEGMENT_KEY"] %>
  <script type="text/javascript">
    window.analytics=window.analytics||[],window.analytics.methods=["identify","group","track","page","pageview","alias","ready","on","once","off","trackLink","trackForm","trackClick","trackSubmit"],window.analytics.factory=function(t){return function(){var a=Array.prototype.slice.call(arguments);return a.unshift(t),window.analytics.push(a),window.analytics}};for(var i=0;i<window.analytics.methods.length;i++){var key=window.analytics.methods[i];window.analytics[key]=window.analytics.factory(key)}window.analytics.load=function(t){if(!document.getElementById("analytics-js")){var a=document.createElement("script");a.type="text/javascript",a.id="analytics-js",a.async=!0,a.src=("https:"===document.location.protocol?"https://":"http://")+"cdn.segment.com/analytics.js/v1/"+t+"/analytics.min.js";var n=document.getElementsByTagName("script")[0];n.parentNode.insertBefore(a,n)}},window.analytics.SNIPPET_VERSION="2.0.9",
    window.analytics.load("<%= ENV["SEGMENT_KEY"] %>");
    window.analytics.page();
  </script>
<% end %>

app/views/application/_flashes.html.erb
<% if flash.any? %>
  <div class="flashes">
    <% user_facing_flashes.each do |key, value| -%>
      <div class="flash-<%= key %>"><%= value %></div>
    <% end -%>
  </div>
<% end %>

app/views/application/_javascript.html.erb
<%= javascript_include_tag :application %>

<%= yield :javascript %>

<%= render "analytics" %>

<% if Rails.env.test? %>
  <%= javascript_tag do %>
    $.fx.off = true;
    $.ajaxSetup({ async: false });
  <% end %>
<% end %>

app/views/application/_navbar.html.erb
<header class="centered-navigation" role="banner">
  <div class="centered-navigation-wrapper">
    <%= link_to root_path, class: "mobile-logo" do %>
      <img src="https://raw.githubusercontent.com/thoughtbot/refills/master/source/images/placeholder_logo_3_dark.png" alt="Logo image">
    <% end %>
    <a href="javascript:void(0)" id="js-centered-navigation-mobile-menu" class="centered-navigation-mobile-menu">MENU</a>
    <nav role="navigation">
      <ul id="js-centered-navigation-menu" class="centered-navigation-menu show">
        <li class="nav-link"><%= link_to 'Read Reviews', reviews_path %></li>
        <li class="nav-link logo">
          <%= link_to root_path, class: 'logo' do %>
            <img src="https://raw.githubusercontent.com/thoughtbot/refills/master/source/images/placeholder_logo_3_dark.png" alt="Logo image">
          <% end %>
        </li>
        <li class="nav-link"><%= link_to 'Write a Review', new_review_path %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="ROBOTS" content="NOODP" />
  <meta name="viewport" content="initial-scale=1" />
  <%#
    Configure default and controller-, and view-specific titles in
    config/locales/en.yml. For more see:
    https://github.com/calebthompson/title#usage
  %>
  <title><%= title %></title>
  <%= stylesheet_link_tag :application, media: "all" %>
  <%= csrf_meta_tags %>
</head>
<body class="<%= body_class %>">
  <%= render 'navbar' -%>
  <%= render "flashes" -%>
  <div class='outer-content'>
    <div class='content'>
      <%= yield %>
    </div>
  </div>
  <%= render "javascript" %>
</body>
</html>

app/views/reviews/_form.html.erb
<%= simple_form_for(@review) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :body, label: "What's it like working with Troy?" %>
    <%= f.input :name %>
    <%= f.input :relationship %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, 'Leave Review' %>
  </div>
<% end %>

app/views/reviews/_review.html.erb
<div class='review'>
  <div class='quote no-close-quote'>
    <%= review.body %>
  </div>

  <div class='source'>
    <div class='source-name'>
      - <%= review.name %>
  </div>

  <div class='source-relationship'>
    <%= review.relationship %>
  </div>
  </div>
</div>

app/views/reviews/edit.html.erb
<h1>Editing Review</h1>

<%= render 'form' %>

<%= link_to 'Show', @review %> |
<%= link_to 'Back', reviews_path %>

app/views/reviews/index.html.erb
<%= render @reviews %>

app/views/reviews/new.html.erb
<%= render 'form' %>

app/views/reviews/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Body:</strong>
  <%= @review.body %>
</p>

<p>
  <strong>Name:</strong>
  <%= @review.name %>
</p>

<p>
  <strong>Relationship:</strong>
  <%= @review.relationship %>
</p>

<%= link_to 'Edit', edit_review_path(@review) %> |
<%= link_to 'Back', reviews_path %>

app/views/static_pages/home.html.erb
<div class="hero">
  <div class="hero-inner">
    <a href="" class="hero-logo selfie"><%= image_tag 'avatar.jpg' %></a>
    <div class="hero-copy">

      <h1>Have you worked with Troy Rosenberg?</h1>

      <p class='explanation'>
      We are looking for reviews of your experiences of working with Troy Rosenberg. Simply write up what it is like to work with Troy!
      </p>

      <div class='review-banner'>
        <%= link_to 'Write a Review!', new_review_path %>
      </div>

    </div>
      <div class='get-inspired'>
        Need some inspiration? <%= link_to 'Check out what everyone else is saying', reviews_path, id: 'inspiration-link' %>
    </div>
  </div>
</div>